version: "3.4"

services:
  php:
    build:
      context: "./"
      dockerfile: "./docker/php/Dockerfile"
    volumes:
      - ".:/app"
    command: "php -S 0.0.0.0:80 -t public -c .docker/php/php.ini"
    ports:
      - "80:80"
    environment:
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/app.db"
      PHP_XDEBUG_DEFAULT_ENABLE: "1"
      PHP_XDEBUG_REMOTE_ENABLE: "1"
      PHP_XDEBUG_REMOTE_HOST: "172.18.0.1"
      SERVER_NAME: "app.dev"
      PHP_IDE_CONFIG: "serverName=app.dev"
      APP_ENV: "dev"

  npm:
    restart: "no"
    build:
      context: "./"
      dockerfile: "./docker/frontend/Dockerfile"
    command: "sh -c 'npm install && npm start'"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

