FROM node:15.5-buster

WORKDIR /app/

# Install dependencies
# COPY package.json yarn.lock /app/

# RUN npm install

# Add rest of the client code
#COPY . /app/

#RUN npm install --unsafe-perm -g sass-loader node-sass

EXPOSE 3000

# CMD npm start
